# Generated by Django 3.0.6 on 2020-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('post_desc', models.CharField(max_length=5000)),
                ('post_author', models.CharField(max_length=50)),
                ('post_heading_1', models.CharField(max_length=50)),
                ('post_desc_1', models.CharField(max_length=5000)),
                ('post_heading_2', models.CharField(max_length=50)),
                ('post_desc_2', models.CharField(max_length=5000)),
                ('post_heading_3', models.CharField(max_length=50)),
                ('post_desc_3', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
