# Generated by Django 3.0.6 on 2020-07-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='post_HEADING',
        ),
    ]
