# Generated by Django 3.0.6 on 2020-07-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200704_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_HEADING',
            new_name='post_heading',
        ),
    ]
