# Generated by Django 3.0.6 on 2020-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order123',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
